# Generated by Django 3.0.8 on 2020-08-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200817_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='titile',
            new_name='title',
        ),
    ]
